2024-08-28 10:51:38 - INFO - log set up done, start running the file
2024-08-28 10:51:38 - ERROR - cannot import name 'second_check' from 'checks' (/Users/shauncai/Desktop/id_project/PEXA/checks.py)
2024-08-28 10:51:38 - INFO - Connection to database was done
2024-08-28 10:51:38 - INFO - Try to execute first check
2024-08-28 10:51:38 - INFO - first check done
